### ISSUE TITLE
Unsupported Version 19041.1806

### ISSUE THREAD

**Issue by ACEACE-code** [QwertyTheCoder/Minecraft-bedrock-cracked#1]

**Comment by QwertyTheCoder** [comment]
@ACEACE-code i may not be able to help today cause am busy in real life

I will respond to you within 2 working days

**Comment by QwertyTheCoder** [comment]
1. Download this zip
   [19041.1806.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/9778702/19041.1806.zip)

3. Extract this zip containing dlls in the following directory
   C:\ProgramData\MCenters\Methods\Dll
Make sure to extract normally using "extract here" mode
