### ISSUE TITLE
Unsupported version 19041.1806

### ISSUE THREAD

**Issue by SirCartier** [QwertyTheCoder/Minecraft-bedrock-cracked#11]
![B972F9D7-CEA1-4314-B7C6-19D2D795C1C7](https://user-images.githubusercontent.com/122203478/211189783-54d25d0c-19c5-4725-ac6d-08a6facc5637.jpeg)

**Comment by QwertyTheCoder** [comment]
[19041.1806.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/10368157/19041.1806.zip)

1.  Download the zip and copy it to "C:\ProgramData\MCenters\Methods\Dll"

2.  After copying, do a "extract here" using WinRAR or 7zip.

3.  After everything's done, open the launcher and try again reinstalling, it may look like its frozen a moment of time but it will install.
