### ISSUE TITLE
Unsupported Version 19041.2075 (Actual Windows Version Is 19045.2364)

### ISSUE THREAD

**Issue by TPSkeleton** [QwertyTheCoder/Minecraft-bedrock-cracked#14]

**Comment by QwertyTheCoder** [comment]
Refer To This
https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/issues/3

**Comment by TPSkeleton** [comment]
i tried the stuff there and it didnt work, putting the stuff in the dll folder just gave me the same error as before and trying to manually replace the dll it just said i didnt have permission or smth along those lines

**Comment by QwertyTheCoder** [comment]
@TPSkeleton make sure when you extract the zip, you extract in "Extract here" mode please
try this with this
[19041.2075.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/10418541/19041.2075.zip)
if doesnt works try this
[19041.2075.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/10418545/19041.2075.zip)

**Comment by QwertyTheCoder** [comment]
also delete the folder extrated before using the second zip

**Comment by TPSkeleton** [comment]
first one worked! tysm for helping

**Comment by QwertyTheCoder** [comment]
@TPSkeleton You're Welcome mate.
