### ISSUE TITLE
Unsupported version 19041.2075 (Windows Settings version 19045.2364)

### ISSUE THREAD

**Issue by aaroncorbin** [QwertyTheCoder/Minecraft-bedrock-cracked#15]
MCenters install hack not working for me, I see a few others have a similar error
![image](https://user-images.githubusercontent.com/122656545/212446713-84f1c696-c737-47c4-aaa7-ef3d16765d92.png)

**Comment by QwertyTheCoder** [comment]
refer to this please 
https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/issues/3

**Comment by aaroncorbin** [comment]
It worked, up and running now. Thank you

**Comment by QwertyTheCoder** [comment]
@aaroncorbin you're welcome :)
