### ISSUE TITLE
Dev mode not needed

### ISSUE THREAD

**Issue by ErrorLab** [QwertyTheCoder/Minecraft-bedrock-cracked#165]
You dont need developer mode to use the hack 👍 
![Screenshot 2024-07-04 172212](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/assets/174748641/99e6ad48-de2e-418f-8270-1f65046d43d8)

**Comment by ErrorLab** [comment]
Can u pls comment here?

**Comment by QwertyTheCoder** [comment]
Well, it's actually for the times when appx doesn't install.
