### ISSUE TITLE
unsupported version 19041.2075

### ISSUE THREAD

**Issue by BeanQan69** [QwertyTheCoder/Minecraft-bedrock-cracked#17]
help me it shows me this prompt but my win version is 19045.2486 and windows.applicationmodel.store.dll is 10.0.1904.2075
here is the log->
[Logs.txt](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/10608400/Logs.txt)

**Comment by blahblah60** [comment]
Go to the dll files and copy them then patch them on IDA.

**Comment by BeanQan69** [comment]
elaborate pls what is ida 
sorry im stupid

**Comment by IchorDragon** [comment]
> 

please explain further, I don't understand how

**Comment by QwertyTheCoder** [comment]
@IchorDragon @BeanQan69 
[19041.2075.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/10785615/19041.2075.zip)
Have this file
and unzip the file in "C:\ProgramData\MCenters\Methods\Dll" in "Extract Here" mode

**Comment by IchorDragon** [comment]
@QwertyTheCoder I placed it, but this time Unsupported Version 19041.2546

**Comment by QwertyTheCoder** [comment]
@IchorDragon Oh, i have the file
[19041.2546.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/10792691/19041.2546.zip)
Extract the zip here, using extract here method.
"C:\ProgramData\MCenters\Methods\Dll"

**Comment by IchorDragon** [comment]
Mod Installed, thank you so much

**Comment by QwertyTheCoder** [comment]
@IchorDragon  Does it work now?

**Comment by IchorDragon** [comment]
@QwertyTheCoder sorry for late reply and yes! cracked version works wonderfully

**Comment by QwertyTheCoder** [comment]
@IchorDragon Glad to know!
