### ISSUE TITLE
Unsupported version 19041.2546

### ISSUE THREAD

**Issue by loneneuron** [QwertyTheCoder/Minecraft-bedrock-cracked#18]
Hi again, after updating Windows the old DLLs stopped working.
I tried following [this](https://www.youtube.com/watch?v=oZ7IAIaj6Uc) YouTube tutorial, but IDA began complaining about the PDB file missing.
After that I tried using https://github.com/rajkumar-rangaraj/PDB-Downloader, but it just says that the PDB file couldn't be found.
What do I do? Can you kindly upload the DLL? And what about the IDA error (I don't want to come to you every time I update Windows :P)? Thanks.

**Comment by blahblah60** [comment]
You don't have to worry about the PDB files. Just click "no" on IDA and you're good to go.

**Comment by blahblah60** [comment]
> 

You don't have to worry about the PDB files. Just click "no" on IDA and you're good to go.

**Comment by loneneuron** [comment]
Then why does it show this error when opening the string in graph mode?
```
IDA failed to display the program in graph mode.
Only instructions belonging to functions can be displayed in graph mode.
For other program items IDA uses the text representation.
```
I was thinking that the PDB files had debugging symbols which can be used to get the function assembly or something.

**Comment by loneneuron** [comment]
Found the problem, after finding the string location I wasn't actually entering the function call. M Centers is working again.

**Comment by QwertyTheCoder** [comment]
@loneneuron 
ik you are already dont with the problem, but still for my sake :)
[19041.2546.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/10785510/19041.2546.zip)

**Comment by loneneuron** [comment]
> @loneneuron ik you are already dont with the problem, but still for my sake :) [19041.2546.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/10785510/19041.2546.zip)

Is that the default DLL or the cracked one? Here's mine if you need it: 
[Windows.ApplicationModel.Store.dll.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/10807319/Windows.ApplicationModel.Store.dll.zip)

**Comment by QwertyTheCoder** [comment]
@loneneuron those are edited ones.
