### ISSUE TITLE
Cannot Install VCLibs Package | M Centers says i do not have .NET Core

### ISSUE THREAD

**Issue by IsaacPar** [QwertyTheCoder/Minecraft-bedrock-cracked#19]
I was following the steps in the **Installation** part when i tried to download the [third link](https://www.microsoft.com/en-sa/download/confirmation.aspx?id=102159), it just downloaded a Readme.txt file leading to [another link](https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/cpp/libraries/c-runtime-packages-desktop-bridge#how-to-install-and-update-desktop-framework-packages) which doesn't tell me anything important, also, when i try to open M Centers it gives an error saying that i do not have .NET Core, but i have even made C# Development in my computer (And it requires .NET) so what do i do?

**Comment by blahblah60** [comment]
Same PROBLEM I cannot install III. [Microsoft Visual C++ UWP Runtime] or what? how to install the third Microsoft Visual. Nevertheless, I tried following all the steps and finally opened Minecraft but it says that Minecraft is currently not available in your account. Error code: 0x803F8001. Btw I'm using Windows 11 22H2, 22621.608.

**Comment by blahblah60** [comment]
> I was following the steps in the **Installation** part when i tried to download the [third link](https://www.microsoft.com/en-sa/download/confirmation.aspx?id=102159), it just downloaded a Readme.txt file leading to [another link](https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/cpp/libraries/c-runtime-packages-desktop-bridge#how-to-install-and-update-desktop-framework-packages) which doesn't tell me anything important, also, when i try to open M Centers it gives an error saying that i do not have .NET Core, but i have even made C# Development in my computer (And it requires .NET) so what do i do?

Try downloading this 
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-3.1.32-windows-x64-installer?cid=getdotnetcore

**Comment by IsaacPar** [comment]
Now ive done it but it says that my Windows 11 version is not supported

**Comment by Max-RM** [comment]
> Я сделал это, но он говорит, что моя версия Windows 11 не поддерживается

Try this https://download.visualstudio.microsoft.com/download/pr/b70ad520-0e60-43f5-aee2-d3965094a40d/667c122b3736dcbfa1beff08092dbfc3/dotnet-sdk-3.1.426-win-x64.exe

I'm on win11 it's helped me
