### ISSUE TITLE
Failed Opening Minecraft, It says "Check your account"

### ISSUE THREAD

**Issue by blahblah60** [QwertyTheCoder/Minecraft-bedrock-cracked#20]
![Screenshot (1)](https://user-images.githubusercontent.com/36565816/216815459-10f8b53c-921f-4eb9-9b38-fff42cccdc33.png)
I already did everything except for installing the III. [Microsoft Visual C++ UWP Runtime] when downloading gives me a readme.txt file.
Windows.ApplicationModel.Store 22621.608 (I patched it myself PERFECTLY)
[22621.608.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/10610785/22621.608.zip)

Same thing happened to my Win 10 PC (dll files downloaded from your github)
Is it required to install Microsoft Visual C++ UWP Runtime?

**Comment by CYRUS-14** [comment]
same happening for me

**Comment by blahblah60** [comment]
> same happening for me

@CYRUS-14 I fixed the problem you just have to get the trial for Minecraft first!

**Comment by CYRUS-14** [comment]
> > same happening for me
> 
> @CYRUS-14 I fixed the problem you just have to get the trial for Minecraft first!
By trial do you mean trial from microsoft store?

**Comment by CYRUS-14** [comment]
ah yes it worked! thanks a lot @blahblah60 !

**Comment by QwertyTheCoder** [comment]
@blahblah60 Glad to see that you helped :), and the solution was perfect
