### ISSUE TITLE
Crack dont work on v1.19.60 

### ISSUE THREAD

**Issue by firmanjml** [QwertyTheCoder/Minecraft-bedrock-cracked#21]
I updated the client and it doesn't work anymore, but when I down grade to v1.19.51.1 the crack work just fine.
Is there a way that would make the crack work on 1.19.60?

**Comment by K0r1g4n** [comment]
For those that are looking how to downgrade, you can follow this howto: https://www.youtube.com/watch?v=rzmA87Fu8fo
It (the downgrade) worked for me to.

**Comment by QwertyTheCoder** [comment]
@firmanjml signing up for minecraft trial from ms store will work for sure
