### ISSUE TITLE
appx file not installing

### ISSUE THREAD

**Issue by Hyuga311** [QwertyTheCoder/Minecraft-bedrock-cracked#22]
When using the mclauncher the launcher keeps on deleting the appx file automatically and cant install any appx file on windows, windows isntaller keeps freezing.

**Comment by QwertyTheCoder** [comment]
@Hyuga311 use
https://github.com/bernarddesfosse/onix_compatible_appx/releases

**Comment by mhyk55** [comment]
> @Hyuga311 use https://github.com/bernarddesfosse/onix_compatible_appx/releases

can u help me bro
