### ISSUE TITLE
Unsupported Version 19041.2546

### ISSUE THREAD

**Issue by xXJeS4sXxYT** [QwertyTheCoder/Minecraft-bedrock-cracked#23]
![Annotation 2023-02-19 020759](https://user-images.githubusercontent.com/96096645/219936615-fd106e26-046d-4896-8328-114c5c5e3f39.png)

**Comment by QwertyTheCoder** [comment]
@xXJeS4sXxYT i have the files for your system :)
[19041.2546.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/10785362/19041.2546.zip)
extract to "C:\ProgramData\MCenters\Methods\Dll" this folder and make sure to use "extract here" type extraction.
