### ISSUE TITLE
m center 4.0 missing file

### ISSUE THREAD

**Issue by IchorDragon** [QwertyTheCoder/Minecraft-bedrock-cracked#24]
window, win 10, version tested: 1.19.60

im doing exact thing from the readme.md but when I open M center, it says missing the .NET core, I clicked "okay" to download but it never start downloading it, so I download it manually, I downloaded NET Core 7.0 but still error, anything I missed or did I downloaded the wrong thing?

**Comment by QwertyTheCoder** [comment]
@IchorDragon Hey, am wondering if you resolved this issue? if the issue still persists feel free to reopen it.

**Comment by IchorDragon** [comment]
> @IchorDragon Hey, am wondering if you resolved this issue? if the issue still persists feel free to reopen it.

yes, it's resolved, I noticed that someone asked the similar question and I downloaded the version that someone answered him, no worries, goes well

**Comment by QwertyTheCoder** [comment]
@IchorDragon NOICEEE
