### ISSUE TITLE
Unsupported Version 19041.2546

### ISSUE THREAD

**Issue by josu914** [QwertyTheCoder/Minecraft-bedrock-cracked#29]
![image](https://user-images.githubusercontent.com/96672608/221400410-df251e90-1aed-48d1-98de-7891b5cadaa2.png)

here's the zip file created by the "main.bat": [19045.2604.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/10833274/19045.2604.zip)

**Comment by QwertyTheCoder** [comment]
@josu914 
[19041.2546.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/10842793/19041.2546.zip)
your edited files,
 follow---
 Extract the zip at "C:\ProgramData\MCenters\Methods\Dll\" using "extract here" option using winrar/7z/other

**Comment by josu914** [comment]
Thank you for your responseee... but unfortunately when i install hack, the MCenter crashes at 50%.

**Comment by QwertyTheCoder** [comment]
@josu914 Can you send the log file / log text

**Comment by josu914** [comment]
Here it is: [Logs.txt](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/10850707/Logs.txt)

**Comment by QwertyTheCoder** [comment]
@josu914 looks normal, try again maybe, have you tried running minecraft once btw?

**Comment by QwertyTheCoder** [comment]
@josu914 You can sign up for minecraft trial at microsoft store to fix it ( sounds pretty stupid but still.
