### ISSUE TITLE
Unsupported Version 19041.2075

### ISSUE THREAD

**Issue by Polytelus** [QwertyTheCoder/Minecraft-bedrock-cracked#3]
My Windows version is actually **19045.2130**, _Windows 10 22H2_.
Clicking `Install Hack` on the launcher fails installation.

Any help to make me run it is welcome.

**Comment by MTM828** [comment]
Same here.

@QwertyTheCoder Man, the new UI is WAY better than the old UI. Same goes for the rest of the launcher. I haven't had a chance to try it until now because I was on FreeBSD, great work! Would be nice to have this issue fixed.

**Comment by QwertyTheCoder** [comment]
Am busy right now, give me 4 hours please.

**Comment by QwertyTheCoder** [comment]
@MTM828 @Polytelus 
I REQUEST YOU THESE FILES FROM YOUR WINDOWS, SO I CAN CRACK THEM
You can provide me according to the architecture of your system(windows) whether x64 or x86(32).
-----------------------------------------------------------------
x64
"C:\Windows\System32\Windows.ApplicationModel.Store.dll"
OR
x86(32bit)
"C:\Windows\SysWOW64\Windows.ApplicationModel.Store.dll"
FROM THESE DLL (S)

**Comment by MTM828** [comment]
[Windows.ApplicationModel.Store.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/10338209/Windows.ApplicationModel.Store.zip)

I'm busy with exams. Take your time.
Note that my Windows version is __19041.1086__, NOT 19041.2075.

**Comment by QwertyTheCoder** [comment]
> [Windows.ApplicationModel.Store.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/10338209/Windows.ApplicationModel.Store.zip)
> 
> I'm busy with exams, so I might take a while to respond. Note that my Windows version is **19041.1806**, NOT 19041.2075. Sorry I mixed up between the two.
@MTM828 
Oh, I wanted to know the version code, which the launcher gave as an error.
I will just crack the dll for now

**Comment by MTM828** [comment]
> Oh, I wanted to know the version code, which the launcher gave as an error.

Sorry, that's what I meant. 😵

**Comment by QwertyTheCoder** [comment]
[19041.1806.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/10354602/19041.1806.zip)
Here's your dll for x64
1.  Download the zip and copy it to "C:\ProgramData\MCenters\Methods\Dll"
2.  After copying, do a "extract here" using WinRAR or 7zip

3.  After everything's done, open the launcher and try again reinstalling, it may look like its frozen a moment of time but it will install.

If still doesnt works copy the folder generated at step 2 in the same directory and then rename it to the error code(version) returned by the M Centers Launcher
@MTM828

**Comment by MTM828** [comment]
Installing hack crashes with this log:
```
Starting Operation: 	Taking Permissions of C:\Windows\System32\Windows.ApplicationModel.Store.dll
Process Started
Output Recieved:	
Output Recieved:	SUCCESS: The file (or folder): "C:\Windows\System32\Windows.ApplicationModel.Store.dll" now owned by user "DESKTOP-GFNFFT5\Mustafa".
Output Recieved:	processed file: C:\Windows\System32\Windows.ApplicationModel.Store.dll
Output Recieved:	Successfully processed 1 files; Failed processing 0 files
Output Recieved:	
Error Recieved:	
Ended Operation: 	Taking Permissions ofC:\Windows\System32\Windows.ApplicationModel.Store.dll
Starting Operation: 	Verify Permissions of C:\Windows\System32\Windows.ApplicationModel.Store.dll
File is Owned
Ended Operation: 	Verify Permissions of C:\Windows\System32\Windows.ApplicationModel.Store.dll
Starting Operation: 	Delete C:\Windows\System32\Windows.ApplicationModel.Store.dll
Unable to end Process Idle
Unable to end Process System
Unable to end Process Registry
Unable to end Process smss
Unable to end Process csrss
Unable to end Process wininit
Unable to end Process services
Unable to end Process Memory Compression
Unable to end Process MsMpEng
Unable to end Process NisSrv
Unable to end Process SecurityHealthService
Unable to end Process svchost
Unable to end Process SgrmBroker
Unable to end Process svchost
Unable to end Process svchost
Unable to end Process csrss
Unable to end Process svchost
Process Ending Completed
File Deleted
Ended Operation: 	Delete C:\Windows\System32\Windows.ApplicationModel.Store.dll
Starting Operation: 	Replace file C:\Windows\System32\Windows.ApplicationModel.Store.dll   with x64 Mode: True
File Replaced
Ended Operation: 	Replace file C:\Windows\System32\Windows.ApplicationModel.Store.dll   with x64 Mode: True
Starting Operation: 	Taking Permissions of C:\Windows\SysWOW64\Windows.ApplicationModel.Store.dll
Starting Operation: 	Verify Permissions of C:\Windows\SysWOW64\Windows.ApplicationModel.Store.dll
Starting Operation: 	Delete C:\Windows\SysWOW64\Windows.ApplicationModel.Store.dll
Unable to end Process Idle
Unable to end Process System
Unable to end Process Registry
Unable to end Process smss
Unable to end Process csrss
Unable to end Process wininit
Unable to end Process services
Unable to end Process Memory Compression
Unable to end Process MsMpEng
Unable to end Process NisSrv
Unable to end Process SecurityHealthService
Unable to end Process svchost
Unable to end Process SgrmBroker
Unable to end Process svchost
Unable to end Process svchost
Unable to end Process csrss
Unable to end Process svchost
Process Ending Completed
File Deleted
Ended Operation: 	Delete C:\Windows\SysWOW64\Windows.ApplicationModel.Store.dll
Starting Operation: 	Replace file C:\Windows\SysWOW64\Windows.ApplicationModel.Store.dll   with x64 Mode: False
```
:(

**Comment by QwertyTheCoder** [comment]
If this occurs you can do this thing manually, move the dll from the x64 folder to the C:\Windows\System32\

**Comment by MTM828** [comment]
It's still not working, after copying `C:\ProgramData\MCenters\Methods\Dll\19041.2075\x64\Windows.ApplicationModel.Store.dll` to `C:\Windows\System32` and `C:\Windows\SysWOW64` it shows `Minecraft is currently not available in your account. Make sure you are signed in to the Microsoft Store and try again. Here's the error code, in case you need it: 0x803F8001` when running Minecraft.

Could it be because I'm using an offline account? And thanks for the help, greatly appreciate it.

**Comment by QwertyTheCoder** [comment]
@MTM828 you can now try sign-in to ms store and going to 'minecraft for windows' and applying for trial. this may work cause it also happened to me too, then it worked.

You did the System32 folder dll replacement good but,

One more thing, the file was x64 and in SysWOW64 there are 32 bit files :/ you replaced a 32 bit file with 64 bit file

**Comment by MTM828** [comment]
Worked like a charm! Thanks dude. :)
![Minecraft 07_01_2023 11_06_02](https://user-images.githubusercontent.com/71281115/211147110-4b7b248e-9fe0-4edb-90e4-9ff7445dc57f.png)
Will deleting the hack repair the SysWOW64 DLLs? How about an `sfc` scan?
Though I don't think losing the original DLLs caused any damage.

**Comment by QwertyTheCoder** [comment]
@MTM828 COONGRATS, well I dont actually know how the dll can be repaired, but I guess you can run DISM online repair search it on internet, when the repair is completed you can replace only the System32 dll again.

I think the corrupted dll wont dive you into problems because there are very less programs which run on 32 bit.

**Comment by QwertyTheCoder** [comment]
@MTM828 And Sir, thank you too for cooperating with me & waiting patiently for my replies.

**Comment by MTM828** [comment]
> I think the corrupted dll wont dive you into problems because there are very less programs which run on 32 bit.

Good thing I don't use MS Store that much anyway.

> @MTM828 And Sir, thank you too for cooperating with me & waiting patiently for my replies.

You're welcome. 😊

**Comment by blahblah60** [comment]
Hi! what do you mean by 'minecraft for windows'? should I download the Minecraft Launcher in MS store? or what?

**Comment by loneneuron** [comment]
Hit `Download APPX` in M Centers and it should take you to the download links, otherwise you can download the MC Bedrock free trial from MS Store, the launcher should unlock the full game.

**Comment by IchorDragon** [comment]
> I REQUEST YOU THESE FILES FROM YOUR WINDOWS, SO I CAN CRACK THEM
> You can provide me according to the architecture of your system(windows) whether x64 or x86(32).
> x64 "C:\Windows\System32\Windows.ApplicationModel.Store.dll" OR x86(32bit) "C:\Windows\SysWOW64\Windows.ApplicationModel.Store.dll" FROM THESE DLL (S)

@QwertyTheCoder 
[Windows.ApplicationModel.Store.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/10779613/Windows.ApplicationModel.Store.zip)
please help

**Comment by QwertyTheCoder** [comment]
@loneneuron @blahblah60 sometimes the newer versions of minecraft which are above than 1.19.40 require you to sign up for minecraft trial versions from ms store.

**Comment by QwertyTheCoder** [comment]
@IchorDragon Hello, am here to help you, can you please elaborate on which topic you need help?

**Comment by IchorDragon** [comment]
> @IchorDragon Hello, am here to help you, can you please elaborate on which topic you need help?

yes, when I do "install hack", it says unsupported, connected to #17 which is unsupported version even tried to use the file you said and did exactly what you said

**Comment by blahblah60** [comment]
@IchorDragon Can you please explain further? and upload a screenshot for the specific problem. Also, be sure you have both of the patched DLL files of x86 and x64.
