### ISSUE TITLE
Can't extract appx file

### ISSUE THREAD

**Issue by dietznuts1234** [QwertyTheCoder/Minecraft-bedrock-cracked#31]

**Comment by dietznuts1234** [comment]
it has been extracting that file for more than 10 minutes is it normal?

**Comment by dietznuts1234** [comment]
it has just finished extracting and now it won't launch .....

**Comment by QwertyTheCoder** [comment]
Hello @dietznuts1234 
Don't pay attention towards that error,
simply just go to the app's directory where it is being ran from and
then install the appx file downloaded

**Comment by QwertyTheCoder** [comment]
@dietznuts1234 or download the version appx from https://github.com/bernarddesfosse/onix_compatible_appx/releases
then install it
