### ISSUE TITLE
Can't download .net core

### ISSUE THREAD

**Issue by VortexPh123** [QwertyTheCoder/Minecraft-bedrock-cracked#32]
is there any other way to download .net core??

**Comment by QwertyTheCoder** [comment]
@VortexPh123 Yeah, remember before opening an issue to see closed issues ;-;

**Comment by QwertyTheCoder** [comment]
@VortexPh123 Check this https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/issues/19
