### ISSUE TITLE
Crack not working after version update

### ISSUE THREAD

**Issue by aaroncorbin** [QwertyTheCoder/Minecraft-bedrock-cracked#33]
Updated from 1.19.51.1, which was the first version I installed using MCLauncher. Got the crack working and it ran fine. However, I updated to the next higher Minecraft version so I can still play realms and the crack is no longer installing. Is there a step I'm missing? MCenters keeps stopping at 83% and closing the window

**Comment by QwertyTheCoder** [comment]
@aaroncorbin You can share me logs of M Centers.

**Comment by aaroncorbin** [comment]
This is the log from my last attempt:

Starting Operation: 	Taking Permissions of C:\Windows\System32\Windows.ApplicationModel.Store.dll
Process Started
Output Recieved:	
Output Recieved:	SUCCESS: The file (or folder): "C:\Windows\System32\Windows.ApplicationModel.Store.dll" now owned by user "AARON-C-LAPTOP\aaron".
Output Recieved:	processed file: C:\Windows\System32\Windows.ApplicationModel.Store.dll
Output Recieved:	Successfully processed 1 files; Failed processing 0 files
Output Recieved:	
Error Recieved:	
Ended Operation: 	Taking Permissions ofC:\Windows\System32\Windows.ApplicationModel.Store.dll
Starting Operation: 	Verify Permissions of C:\Windows\System32\Windows.ApplicationModel.Store.dll
File is Owned
Ended Operation: 	Verify Permissions of C:\Windows\System32\Windows.ApplicationModel.Store.dll
Starting Operation: 	Delete C:\Windows\System32\Windows.ApplicationModel.Store.dll
Unable to end Process Idle
Unable to end Process System
Unable to end Process Registry
Unable to end Process smss
Unable to end Process csrss
Unable to end Process wininit
Unable to end Process csrss
Unable to end Process services
Unable to end Process Memory Compression
Unable to end Process SgrmBroker
Unable to end Process sppsvc
Unable to end Process svchost
Unable to end Process SecurityHealthService
Unable to end Process MsMpEng
Unable to end Process NisSrv
Unable to end Process svchost
Process Ending Completed
File Deleted
Ended Operation: 	Delete C:\Windows\System32\Windows.ApplicationModel.Store.dll
Starting Operation: 	Replace file C:\Windows\System32\Windows.ApplicationModel.Store.dll   with x64 Mode: True
File Replaced
Ended Operation: 	Replace file C:\Windows\System32\Windows.ApplicationModel.Store.dll   with x64 Mode: True
Starting Operation: 	Taking Permissions of C:\Windows\SysWOW64\Windows.ApplicationModel.Store.dll
Starting Operation: 	Verify Permissions of C:\Windows\SysWOW64\Windows.ApplicationModel.Store.dll
Starting Operation: 	Delete C:\Windows\SysWOW64\Windows.ApplicationModel.Store.dll
Unable to end Process Idle
Unable to end Process System
Unable to end Process Registry
Unable to end Process smss
Unable to end Process csrss
Unable to end Process wininit
Unable to end Process csrss
Unable to end Process services
Unable to end Process Memory Compression
Unable to end Process SgrmBroker
Unable to end Process sppsvc
Unable to end Process svchost
Unable to end Process SecurityHealthService
Unable to end Process MsMpEng
Unable to end Process NisSrv
Unable to end Process svchost
Process Ending Completed
File Deleted
Ended Operation: 	Delete C:\Windows\SysWOW64\Windows.ApplicationModel.Store.dll
Starting Operation: 	Replace file C:\Windows\SysWOW64\Windows.ApplicationModel.Store.dll   with x64 Mode: False

**Comment by aaroncorbin** [comment]
My previous 1.19.51 still works with all features but the new version will not allow me to sign in or access paid features

**Comment by aaroncorbin** [comment]
All good now, did some troubleshooting using other answers, did a restart, newest version now working!
