### ISSUE TITLE
Unsupported Version 22000.1516

### ISSUE THREAD

**Issue by mmbepari** [QwertyTheCoder/Minecraft-bedrock-cracked#34]
![Screenshot_1](https://user-images.githubusercontent.com/127887092/225100153-d6eecccb-1f17-4205-9ec3-84aa921a9764.jpg)

Windows 11 Enterprise | 21H2 (Build 22000.1641)

---Log---
Starting Operation:  Checking Version of System Dlls 
Detected 22000.1516
Ended Operation:  Checking Version of System Dlls 
Starting Operation:  Is Dll mode available for 22000.1516
Checking Online
File Downloaded
Unsupported Version
Ended Operation:  Is Dll mode available for 22000.1516

---Main.bat---
[22000.1641.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/10972507/22000.1641.zip)

**Comment by mmbepari** [comment]
> @mmbepari give me some time

No problem, bro. Take all the time you need.

**Comment by QwertyTheCoder** [comment]
@mmbepari here you go,
[22000.1516.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/10983143/22000.1516.zip)
(the same files but with diff name)
[expand.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/10983145/expand.zip)
script: https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/releases/download/v4069/main.zip

1. Download these files,
2. extract the main.zip
3. copy the main_2.bat batch script to the folder where the 'zips' of the dll files are placed
4. run the main_2.bat file

**Comment by mmbepari** [comment]
Thank you so much for all the work. It works flawlessly now.

**Comment by QwertyTheCoder** [comment]
@mmbepari You are welcome, also thank you for your responses.

**Comment by JoinFall22** [comment]
> @mmbepari вот вам, [22000.1516.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/10983143/22000.1516.zip) (те же файлы, но с именем diff) [развернуть.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/10983145/expand.zip) скрипт: https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/releases/download/v4069/main.zip
> 
> 1. Загрузите эти файлы,
> 2. извлечь основной.zip
> 3. Скопируйте пакетный сценарий main_2.bat в папку, в которую помещены ZIP-файлы DLL-файлов
> 4. Запустите файл main_2.bat

**Comment by JoinFall22** [comment]
> @mmbepari вот вам, [22000.1516.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/10983143/22000.1516.zip) (те же файлы, но с именем diff) [развернуть.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/10983145/expand.zip) скрипт: https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/releases/download/v4069/main.zip
> 
> 1. Загрузите эти файлы,
> 2. извлечь основной.zip
> 3. Скопируйте пакетный сценарий main_2.bat в папку, в которую помещены ZIP-файлы DLL-файлов
> 4. Запустите файл main_2.bat

where is this folder where you need to throw main_2.bat

**Comment by mmbepari** [comment]
> where is this folder where you need to throw main_2.bat

1. You have to unzip the main.zip file.
2. Copy the main_2.bat file into the folder where you unzipped the contents of main.zip.
3. Double-click the main_2.bat file.

**Comment by JoinFall22** [comment]
> > where is this folder where you need to throw main_2.bat
> 
> 1. You have to unzip the main.zip file.
> 2. Copy the main_2.bat file into the folder where you unzipped the contents of main.zip.
> 3. Double-click the main_2.bat file.

I'm wildly sorry, but in which folder should I unzip main.zip? Something is hard for me to reach, can you explain in more detail, thanks in advance

**Comment by mmbepari** [comment]
> I'm wildly sorry, but in which folder should I unzip main.zip? Something is hard for me to reach, can you explain in more detail, thanks in advance. Honestly, I rummaged through everything, but it didn’t work out for me

You can unzip the main.zip file anywhere you like. You can unzip it to your desktop. You need to make sure your Windows version is the same as in this thread. If not, open a new issue as this one is closed.

**Comment by JoinFall22** [comment]
> > I'm wildly sorry, but in which folder should I unzip main.zip? Something is hard for me to reach, can you explain in more detail, thanks in advance. Honestly, I rummaged through everything, but it didn’t work out for me
> 
> You can unzip the main.zip file anywhere you like. You can unzip it to your desktop. You need to make sure your Windows version is the same as in this thread. If not, open a new issue as this one is closed.

The question you just answered I was able to solve, but thanks anyway
