### ISSUE TITLE
Unsupported Version 22621.1194

### ISSUE THREAD

**Issue by timidtlk** [QwertyTheCoder/Minecraft-bedrock-cracked#35]
![error](https://user-images.githubusercontent.com/114370755/225152839-774ce178-3b81-4b77-ac28-2742ce83766b.png)
I'm trying to install hack, but it's throwing this error. In another post, qwerty had asked for two dlls, so I will post it together with the issue: 
[dlls.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/10974284/dlls.zip)

**Comment by QwertyTheCoder** [comment]
[22621.1194.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/10983017/22621.1194.zip)
[expand.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/10983019/expand.zip)
https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/releases/download/v4069/main.zip

@timidtlk 

Download these files,
extract the main.zip 
copy the main_2.bat batch script to the folder where the zips of the dll files are placed
run the main_2.bat file

**Comment by QwertyTheCoder** [comment]
@DefNotAkmal Your windows must be updated until now again.
Give me the error screenshot

**Comment by donovanfourchette** [comment]
hey, i have the same issue with the same code. I did what u said but it still doesnt work. Maybe im not doing it right can u explain with more details plz ?

**Comment by QwertyTheCoder** [comment]
@donovanfourchette 

1. You have to unzip the main.zip file.
2. Copy the main_2.bat file into the folder where you unzipped the contents of main.zip.
3. Double-click the main_2.bat file.


You can unzip the main.zip file anywhere you like. You can unzip it to your desktop. You need to make sure your Windows version is the same as in this thread. If not, open a new issue as this one is closed.

**Comment by timidtlk** [comment]
It's solved, thank you!
