### ISSUE TITLE
Unsupported version 19041.2546 (actual version is 19045.2728)

### ISSUE THREAD

**Issue by Viren070** [QwertyTheCoder/Minecraft-bedrock-cracked#38]
![image](https://user-images.githubusercontent.com/71220264/226181614-62f04623-e3e1-480b-ab65-915782537f1b.png)

files generated by main.bat:
[19045.2728.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/11011227/19045.2728.zip)

**Comment by Viren070** [comment]
I tried modifying the dlls according to this video: https://www.youtube.com/watch?v=oZ7IAIaj6Uc
and got this
[19045.2728.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/11011649/19045.2728.zip)
i put the files under the folder with name 19041.2546 and then it gets stuck at 25% with the command prompt still open and when i close the command prompt it jumps to 41, then after a few seconds it goes to 50% and crashes
[16 32.txt](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/11011662/16.32.txt)

[Logs.txt](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/11011661/Logs.txt)

**Comment by QwertyTheCoder** [comment]
@Viren070 i dont know why people dont check for closed issues.
Just keep on duplicating.

**Comment by Viren070** [comment]
> 

wdym no one else had this version so i couldnt do anything by looking at the closed issues

**Comment by Viren070** [comment]
> > 
> 
> wdym no one else had this version so i couldnt do anything by looking at the closed issues

on about "keep on duplicating" stfu
