### ISSUE TITLE
unsupported version 25336.1000

### ISSUE THREAD

**Issue by lightcaptainguy** [QwertyTheCoder/Minecraft-bedrock-cracked#44]

**Comment by CapMactavish241** [comment]
https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/issues/40
I've explained a fix in the above issue

**Comment by lightcaptainguy** [comment]
where to paste the dll files, sorry i am a bit stupid

**Comment by lightcaptainguy** [comment]
So when will you be able to fix it

**Comment by QwertyTheCoder** [comment]
Can you msg me on any of the social media platforms. @lightcaptainguy

**Comment by Max-RM** [comment]
> _No description provided._

Send your dlls using this

**Comment by Max-RM** [comment]
> [25336.1000.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/11211739/25336.1000.zip)

Hi.

Try to run M centres again

**Comment by lightcaptainguy** [comment]
Okay thank you

**Comment by Max-RM** [comment]
> Okay thank you

Ot works now?

**Comment by lightcaptainguy** [comment]
A question, can we run older versions 

> > Okay thank you
> 
> Ot works now?

A question does it work with older versions too?

**Comment by Max-RM** [comment]
> A question, can we run older versions
> 
> > > Okay thank you
> > 
> > 
> > Ot works now?
> 
> A question does it work with older versions too?

Yea

**Comment by lightcaptainguy** [comment]
Does windows update affect this or not?
