### ISSUE TITLE
Unsupported version 19041.2546 (but mu version 19044.2846)

### ISSUE THREAD

**Issue by Hu1umu1uM** [QwertyTheCoder/Minecraft-bedrock-cracked#45]

**Comment by Hu1umu1uM** [comment]
When i launch Minecraft.exe it write that system not found VCRUNTIME140_1_APP.dll and vccorlib140_app.DLL and MSVCP140_APP.dll and CONCRT140_APP.dll

**Comment by QwertyTheCoder** [comment]
there is no 'minecraft.exe'
moreover, install these files
https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked#installation-of-minecraft--

**Comment by Hu1umu1uM** [comment]
Cant install III. [Microsoft Visual C++ UWP Runtime] IV. [Microsoft Visual C++ Libraries]
