### ISSUE TITLE
Unsupported version 22621.1194

### ISSUE THREAD

**Issue by Isuki777** [QwertyTheCoder/Minecraft-bedrock-cracked#46]
![image](https://user-images.githubusercontent.com/127010839/232198368-93addbd7-b00b-468e-a98f-e919432b42e5.png)

**Comment by Isuki777** [comment]
[22621.1555.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/11238821/22621.1555.zip)
this the zip file created using main1.bat

**Comment by QwertyTheCoder** [comment]
https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/issues/35
