### ISSUE TITLE
win 11 unsupported version 22621.608 fixed

### ISSUE THREAD

**Issue by KushanNahsuk** [QwertyTheCoder/Minecraft-bedrock-cracked#5]
![image](https://user-images.githubusercontent.com/116539619/197453432-f60a2f86-bcd6-47be-b68b-ad0885cb6fa2.png)

**Comment by Hypertext-Assassin-RSS** [comment]
Same hear unable to crack after update

**Comment by QwertyTheCoder** [comment]
@Hypertext-Assassin-RSS 
@KushanNahsuk 
sorry for late reply guys
try to use the old m centers launcher https://github.com/QwertyTheCoder/Minecraft-Bedrock-Crack

**Comment by KushanNahsuk** [comment]
@QwertyTheCoder ty i will try

**Comment by KushanNahsuk** [comment]
@QwertyTheCoder ty it worked and srry for late responce if u are facing the same problem just do the same

**Comment by QwertyTheCoder** [comment]
@KushanNahsuk if it freezes lemme know

**Comment by Hypertext-Assassin-RSS** [comment]
works for me to but I miss the new version fetures

**Comment by Hypertext-Assassin-RSS** [comment]
It worked for me to but miss the features of newer version

**Comment by QwertyTheCoder** [comment]
@Hypertext-Assassin-RSS 😀

**Comment by QwertyTheCoder** [comment]
@Hypertext-Assassin-RSS If it freeezes lemme know

**Comment by QwertyTheCoder** [comment]
@KushanNahsuk 
@Hypertext-Assassin-RSS 
Hey, sorry for disturbing you guys
can I get this DLL so I can crack it?
For x64
"C:\Windows\System32\Windows.ApplicationModel.Store.dll"

And for x86(32bit)
"C:\Windows\SysWOW64\Windows.ApplicationModel.Store.dll"

If you guys upload the DLL please mention whether its from system32 folder or syswow64
Thank you.

**Comment by Hypertext-Assassin-RSS** [comment]
> @KushanNahsuk @Hypertext-Assassin-RSS Hey, sorry for disturbing you guys can I get these DLL(s) so I can crack it? I need both irrespective of bitness x64 "C:\Windows\System32\Windows.ApplicationModel.Store.dll"
> 
> x86(32bit) "C:\Windows\SysWOW64\Windows.ApplicationModel.Store.dll"
> 
> If you guys upload the DLL please mention whether its from system32 folder or syswow64 Thank you.

[Windows.ApplicationModel.Storex64.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/10000969/Windows.ApplicationModel.Storex64.zip)

**Hear You Go 👆**

**Comment by QwertyTheCoder** [comment]
@Hypertext-Assassin-RSS
[22621.608.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/10012207/22621.608.zip)
Here you gooooooo for x64

**Comment by Hypertext-Assassin-RSS** [comment]
Thanks 👍

**Comment by QwertyTheCoder** [comment]
@Hypertext-Assassin-RSS lemme know if it works

**Comment by blahblah60** [comment]
Where is for x86?

**Comment by blahblah60** [comment]
I patched both x64 & x86 for 22621.608
[22621.608.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/10610771/22621.608.zip)

**Comment by QwertyTheCoder** [comment]
@blahblah60 

> Where is for x86?

There is no need of x86, cause no one gonna use win 11 x86 arc

**Comment by QwertyTheCoder** [comment]
> I patched both x64 & x86 for 22621.608 [22621.608.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/10610771/22621.608.zip)

Thank you mate 👍
