### ISSUE TITLE
Unsupported Version 22621.1635

### ISSUE THREAD

**Issue by Dist-fx** [QwertyTheCoder/Minecraft-bedrock-cracked#50]
![Desktop Screenshot 2023 04 27 - 23 28 10 97](https://user-images.githubusercontent.com/112022545/235054933-69ac2411-1ccc-4d87-8e86-a0964df05403.png)

**Comment by QwertyTheCoder** [comment]
@Dist-fx 
https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/releases/download/v4069/main.zip
extract this zip
start the main_1.bat
upload the zip created by it, here itself.

**Comment by K14dash** [comment]
[22621.1702.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/11450571/22621.1702.zip)

**Comment by QwertyTheCoder** [comment]
@K14dash
Can you create another issue for your problem.
And upload that zip there with the error screenshot.

**Comment by K14dash** [comment]
same issue, but the zip created by main_1.bat is this

> [22621.1702.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/11450571/22621.1702.zip)

**Comment by BlackDoma** [comment]
same problem exactly here and here is the zip 
[22621.1702.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/11502472/22621.1702.zip)

**Comment by QwertyTheCoder** [comment]
@BlackDoma @Dist-fx @K14dash 
[expand.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/11528382/expand.zip)
[scripts_v2.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/11528396/scripts_v2.zip)
Extract the scripts_v2.zip and 
move the expand.zip to the same folder as bat files from the scripts_v2.zip

Then run the main_2_expand.bat

**Comment by ChosenProgram** [comment]
same problem
[22631.1972.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/11913781/22631.1972.zip)
![Screenshot 2023-06-30 145632](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/assets/126732466/f8d273ce-2f62-41b3-8bff-2ada66b12b8a)
