### ISSUE TITLE
Free Trial

### ISSUE THREAD

**Issue by DoomCoomer** [QwertyTheCoder/Minecraft-bedrock-cracked#55]
Why do i have a free trial ? wasn't i supposed to get the Full version For free? If it was for just a free trial why is that? why cant i get full for free?

**Comment by QwertyTheCoder** [comment]
@DoomCoomer There must be any error in the process you have followed!
I recommend you to cross check everything.

**Comment by DoomCoomer** [comment]
> @DoomCoomer There must be any error in the process you have followed! I recommend you to cross check everything.

Ok Mate Thanks

**Comment by QwertyTheCoder** [comment]
@DoomCoomer https://discord.gg/m-centers-1040545324743266314
