### ISSUE TITLE
Friends can't connect

### ISSUE THREAD

**Issue by 1ce-one** [QwertyTheCoder/Minecraft-bedrock-cracked#57]
Hey,  I installed your  crack but I'm not able to join friend's servers neither are they able to join me.
I am able to join other servers though.
We are both on the same version.
I'm on pc they are on an Ipad.

**Comment by QwertyTheCoder** [comment]
Hello @1ce-one !
The problem must be with the server, can you check on the server once that, it must be the same version as your friend and your's minecraft version.
Check the whitelist and blacklist of the server too.

**Comment by 1ce-one** [comment]
we both created a world and tried to join each other's worlds. But it just shows unable to connect. We both are on the same version of the game

**Comment by QwertyTheCoder** [comment]
@1ce-one Sorry!, but that won't work.
You can play on servers. like Aternos hosted servers for example.

**Comment by Rafaytec** [comment]
LAN play between people on different interents won't work but if you're signed in with Xbox Live then you can play with anyone as long as you friend them and they too.
