### ISSUE TITLE
Alot of errors when opening version 1.19.81.1

### ISSUE THREAD

**Issue by Insvrrection** [QwertyTheCoder/Minecraft-bedrock-cracked#59]
App re-register failed:
System.I.DirectoryNotFoundException: Could not find a part of the
path 'C:\Users\Charlie
Pritchard \AppData\Local TmpMinecraftLocalState*
at System.IO. Error.WinIOErrorInt32 errorCode, String
maybeFullPath)
at System.IO.FileSystemEnumerableIterator'1.Commoninit0
at System.IO.FileSystemEnumerableiterator 1..ctor(String path, String
originalUserPath, String searchPattern, SearchOption searchOption,
SearchResultHandler 1 resultHandler, Boolean checkHost)
at System.IO.Directory. EnumerateFiles(String path)
at MCLauncher.MainWindow.RestoreMove(String from, String to) in
C\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MC
Launcher MainWindow.xaml.cs:line 253
MCLauncher.MainWindow.RestoreMinecraftDataFromReinstall(String
packageFamily) in
causers dvlan-work Documents oroied< mc.wiversion-sunchermo
Launcher\MainWindow.xaml.cs:line 280
at MCLauncher.MainWindow.<ReRegisterPackage>d__32.MoveNext0
in
Causers avan-work Documents oroied< mc.wiversion-auncheric
Launcher\MainWindow.xaml.cs:line 325
-.. End or stack trace trom previous location where eyception was
Thrown -
at System.Runtime. ExceptionServices.ExceptionDispatchinfo.Throw0
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndD
ebuggerNotification(Task task)
MCLauncher.MainWindow.<>C__DisplayClass23_0.<<InvokeLaunch>b_
0> d.MoveNext in
CAUsers\dylan-workDocuments\projects\mc-w10-version-launcher\MC
TauncherMainwindow.yam.ccinee.

**Comment by QwertyTheCoder** [comment]
@Insvrrection Remove it.
Download appx file from https://github.com/bernarddesfosse/onix_compatible_appx/releases and install it.
Then start minecraft from start menu.
