### ISSUE TITLE
ERROR: .NET Core

### ISSUE THREAD

**Issue by warukoff** [QwertyTheCoder/Minecraft-bedrock-cracked#6]
![2022-11-23 21_12_47-$](https://user-images.githubusercontent.com/118911112/203568292-aed2a328-bfb4-4ea9-af98-0b904a696ae0.png)
It gives an error with .NET Core but I have it installed

**Comment by QwertyTheCoder** [comment]
@warukoff install it then

**Comment by warukoff** [comment]
I installed it but it doesn't work

**Comment by QwertyTheCoder** [comment]
@warukoff try restarting your pc.

**Comment by warukoff** [comment]
I restarted but it doesn't work

**Comment by warukoff** [comment]
Maybe I downloaded the wrong version

**Comment by QwertyTheCoder** [comment]
@warukoff 
https://discord.gg/mMUtdUN2zC
This is official m centers server
You can get help there now i guess cause i have some work right now

**Comment by xXJeS4sXxYT** [comment]
Download this https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-3.1.425-windows-x64-installer and I think it should work (it worked for me)

**Comment by QwertyTheCoder** [comment]
@xXJeS4sXxYT Thanks for the recommending the specific version of msdotnet framework :)
