### ISSUE TITLE
Can not install Microsoft Visual C++ Libraries - 4th link

### ISSUE THREAD

**Issue by PedramZabihi** [QwertyTheCoder/Minecraft-bedrock-cracked#60]
So when I try to install [Microsoft Visual C++ Libraries]-4th link this error comes up in the app installer:
App installation failed with error message: error 0x80073D02: Unable to install because the following apps need to be closed Microsoft.DesktopAppInstaller_1.19.10173.0_x64__8wekyb3d8bbwe. (0x80073d02)
how am I supposed install vclibs if I need to close the App Installer????
, what should I do????

**Comment by QwertyTheCoder** [comment]
@PedramZabihi 
Try restarting your system.
If it doesnt work, then...
1) Turn ON developer mode from windows settings.
2) launch powershell
3) Get-AppXPackage -AllUsers | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}

**Comment by PedramZabihi** [comment]
so i tried what you said, in powershell i got this:
Add-AppxPackage : Deployment failed with HRESULT: 0x80073D02, The package could not be installed because resources it   modifies are currently in use.                                                                                          error 0x80073D02: Unable to install because the following apps need to be closed                                        Microsoft.Windows.ShellExperienceHost_10.0.19041.1949_neutral_neutral_cw5n1h2txyewy.                                    NOTE: For additional information, look for [ActivityId] 45974cc7-8522-0000-f898-97452285d901 in the Event Log or use    the command line Get-AppPackageLog -ActivityID 45974cc7-8522-0000-f898-97452285d901                                     At line:1 char:38                                                                                                       + ...  | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.I ...                                         +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                 + CategoryInfo          : NotSpecified: (C:\Windows\Syst...ppXManifest.xml:String) [Add-AppxPackage], Exception         + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand                                                                                                                              Add-AppxPackage : Deployment failed with HRESULT: 0x80073D02, The package could not be installed because resources it   modifies are currently in use.                                                                                          error 0x80073D02: Unable to install because the following apps need to be closed
Microsoft.Windows.StartMenuExperienceHost_10.0.19041.1023_neutral_neutral_cw5n1h2txyewy.
NOTE: For additional information, look for [ActivityId] 45974cc7-8522-0002-ee9a-97452285d901 in the Event Log or use
the command line Get-AppPackageLog -ActivityID 45974cc7-8522-0002-ee9a-97452285d901
At line:1 char:38
+ ...  | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.I ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Windows\Syst...ppXManifest.xml:String) [Add-AppxPackage], Exception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

Add-AppxPackage : Deployment failed with HRESULT: 0x80073D02, The package could not be installed because resources it
modifies are currently in use.
error 0x80073D02: Unable to install because the following apps need to be closed
MicrosoftWindows.Client.CBS_1000.19041.1000.0_x64__cw5n1h2txyewy.
NOTE: For additional information, look for [ActivityId] 45974cc7-8522-0003-9a9d-97452285d901 in the Event Log or use
the command line Get-AppPackageLog -ActivityID 45974cc7-8522-0003-9a9d-97452285d901
At line:1 char:38
+ ...  | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.I ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Windows\Syst...ppXManifest.xml:String) [Add-AppxPackage], Exception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand


and in app installer i got the same error

**Comment by andrex47** [comment]
in my computer it was the myphone app that did not allow installation of this app, i had to remove it with powershell:
Remove-AppxPackage Microsoft.YourPhone_1.23032.196.0_x64__8wekyb3d8bbwe
and had to add that dependency with powershell too
Add-AppxPackage Microsoft.VCLibs.x64.14.00.Desktop.appx

**Comment by PedramZabihi** [comment]
> 

I got it solved but not like this, i think there was a problem with the provided appx for me, found another file and it got solved

**Comment by QwertyTheCoder** [comment]
@PedramZabihi @andrex47 I will fix this 4th link asap
