### ISSUE TITLE
unsupported version 22621.1635

### ISSUE THREAD

**Issue by HIMsterya** [QwertyTheCoder/Minecraft-bedrock-cracked#61]
![Screenshot (7)](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/assets/88937146/e358643b-39ea-4c3e-b006-6db63d8cfe2c)

**Comment by HIMsterya** [comment]
I've already run the main_1 bat and I got this zip file
[22621.1702.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/11478945/22621.1702.zip)

**Comment by QwertyTheCoder** [comment]
@HIMsterya join 
https://discord.gg/m-centers-1040545324743266314
