### ISSUE TITLE
DLL for my windows version please (DLLs already provided)

### ISSUE THREAD

**Issue by mhm199** [QwertyTheCoder/Minecraft-bedrock-cracked#69]
![image](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/assets/57556087/2de0eaf1-fa13-41f1-b091-3339f3d7715b)
Hi, So I'm on 19045.3030 and when I run MCenters 4 its giving me unsupported error so I would kindly like to request for fix DLLs

[19045.3030.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/11619784/19045.3030.zip)

here is the dlls for my version... thank you I will wait.

**Comment by QwertyTheCoder** [comment]
@mhm199 I will provide the dll asap.

**Comment by QwertyTheCoder** [comment]
[19045.3030.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/11623543/19045.3030.zip)
Here are the dll files.
rename the zip to expand.zip
[scripts_v3.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/11623561/scripts_v3.zip)
unzip the scripts_v3 zip 
if the scripts and the expand.zip are in the same folder then run the main_2_expand.bat
if the scripts and the expand.zip are not in the same folder copy the expand.zip to the unzipped folder. and run main_2_expand.bat
@mhm199

**Comment by mhm199** [comment]
Thank you so much!

**Comment by mhm199** [comment]
Hi! So I accidentally changed my windows version and If you don't mind me kindly asking for new DLLs for my version again😅. Thank you, sorry and I will wait👍. @QwertyTheCoder 
[19045.2965.zip](https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked/files/11720820/19045.2965.zip)

**Comment by QwertyTheCoder** [comment]
@mhm199 Please create a new issue for that, Thank you.
