### ISSUE TITLE
WARNING--TRIED TO DELETE OS!

### ISSUE THREAD

**Issue by PatentOwl** [QwertyTheCoder/Minecraft-bedrock-cracked#87]
So I was installing my trsty little software, with securaty issues oc. I mean the warning was _yellow_... However I installed it and to my surprise, it deleted **operatv4.5system.** But it wanst the launcher it self, it was the modding thingy MCentres. **You can still boot windows only if you go in your bios and boot from your SSD, not Windows Boot Manager**. Be aware out there my friends :)

**Comment by QwertyTheCoder** [comment]
False accusation.
